### ISSUE TITLE
About synopsis

### ISSUE THREAD

**Issue by GabrielNX** [Skylake-dev/mal.py#5]
I got this warn: "synopsis not requested or missing"

**Comment by Skylake-dev** [comment]
This is because by default not all possible fields are requested when searching information on an anime or manga. The idea is to minimize the data transfer by requesting only the data that is going to be used. If you try to print the content of a field that is not present you will get a similar message.
If you want all the fields you can specify so on a per request basis by passing it to the method you are calling or setting it in the client once to use them in all subsequent requests, see examples below.
Also, for some anime not all information is present on MAL, so it can be that in some cases this info is simply not available, check on the corresponding page on the website to see if that's the case.

```python
# all fields requested in all subsequent requests
# use this if you don't want to bother with selecting fields.
client.anime_fields = Field.all_anime()
# also for manga if you need
client.manga_fields = Field.all_manga()

# all fields only in this request
anime = client.get_anime(16498, fields=Field.all_anime())

# can use an arbitrary list of fields, only the specified ones will be requested
my_fields = [Field.num_episodes, Field.start_season, Field.synopsis, Field.source]
anime = client.get_anime(16498, fields=my_fields)
```
Look into `Fields.default_anime()` and `Fields.default_manga()` to see which ones are requested by default.
If you don't have further question please close the issue.
